name: PHPStan

on:
  workflow_dispatch:

jobs:
  phpstan:
    if: github.repository == 'onesiphorus-team/onesiforo-web'
    name: phpstan
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse app --memory-limit=2G --error-format=github -c phpstan.neon.dist
